language: python
python:
    - "2.7"
install: pip install six validictory nose --use-mirrors
script: nosetests
notifications:
    email:
        - jturk@sunlightfoundation.com
        - paultag@sunlightfoundation.com
