language: python
python:
    - "2.7"
    - "3.3"
install: pip install validictory nose --use-mirrors
script: nosetests
notifications:
    email:
        - jturk@sunlightfoundation.com
        - paultag@sunlightfoundation.com
